Silverback\ApiComponentsBundle\Entity\Component\Form:
  attributes:
    output: Silverback\ApiComponentsBundle\Entity\Component\Form
  collectionOperations:
    get: ~
    post: ~
  itemOperations:
    get: ~
    delete: ~
    put: ~
    patch:
      method: PATCH
      path: '/forms/{id}/submit.{_format}'
      requirements:
        id: '[^/]+'
      denormalization_context:
        groups:
          - none
      controller: 'Silverback\ApiComponentsBundle\Action\Form\FormPostPatchAction'
    post:
      method: POST
      path: '/forms/{id}/submit.{_format}'
      requirements:
        id: '[^/]+'
      denormalization_context:
        groups:
          - none
      controller: 'Silverback\ApiComponentsBundle\Action\Form\FormPostPatchAction'
